// ARCHIVO GENERADO POR tools/exportar_modelo.py — NO EDITAR A MANO.
// Espejo legible del modelo AnyLogic. La fuente de verdad es el .alp.

// Option Lists del modelo

enum TipoProducto { JUGO, ACEITE, CASCARA }

enum EstadoPedido { PENDIENTE, RESERVADO, EN_TRANSITO, ENTREGADO, ATRASADO, CANCELADO, EN_PREPARACION, PENDIENTE_PLANIFICACION, PLANIFICADO, EN_EJECUCION, COMPLETADO }

enum EstadoCamion { DISPONIBLE, CARGANDO, VIAJANDO, DESCARGANDO, RETORNANDO }

enum EstadoLote { EN_PLANTA, EN_TRANSITO_DEPOSITO, EN_DEPOSITO, RESERVADO, EN_TRANSITO_PUERTO, ENTREGADOENTREGADO }

enum EstadoEnvio { CREADO, ESPERANDO_CAMION, CARGANDO, EN_TRANSITO, DESCARGANDO, CONSOLIDANDO, RETORNANDO, ENTREGADO, CANCELADO }

enum TipoContenedor { REEFER_40, DRY_HC_40, IMO_DRY_20 }

enum EstrategiaLogistica { SIN_DEFINIR, CONSOLIDACION_PLANTA, CONSOLIDACION_DEPOSITO, CROSS_DOCK_DEPOSITO, CROSS_DOCK_TERMINAL }

enum TipoMovimiento { REUBICACION_PRODUCTO, TRANSPORTE_CROSS_DOCK, CICLO_CONTENEDOR }

enum TipoCamion { CAMION_PRODUCTO, PORTACONTENEDOR }

enum EstadoContenedor { CREADO, ESPERANDO_PROGRAMACION, ESPERANDO_RETIRO_VACIO, EN_TRANSITO_VACIO, ESPERANDO_CARGA, CONSOLIDANDO, EN_TRANSITO_CARGADO, INGRESADO_TERMINAL, EXPORTADO }

enum EstadoPlanLogistico { BORRADOR, FACTIBLE, NO_FACTIBLE, SELECCIONADO, EN_EJECUCION, COMPLETADO, CANCELADO }

enum Naviera { SIN_DEFINIR, MSC, MAERSK, HAPAG_LLOYD, CMA_CGM, ONE }
